####################################################################
#     Prepare service dependencies for development mode            #
####################################################################

# To deploy only dependant services:
# docker-compose -f docker-dev.yml up

version: '3'
services:
  mongo:
    image: mongo
    ports:
    - 27017:27017

  mysql:
    restart: always
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
